### ISSUE TITLE
ssl.SSLError sslv3 alert handshake failure using examdownloader-cli.py

### ISSUE THREAD

**Issue by hongshaoyang** [nusmodifications/nus-exams-downloader#5]
not sure if this is out of date or what but i just tried to play around with this repo. NUS stepping up on its security whoop whoop

```
$ python examdownloader-cli.py IS4240 e000XXXX
Enter password for e000XXXX:
Connecting to NUS Library Portals...
Traceback (most recent call last):
  File "examdownloader-cli.py", line 36, in <module>
    startDownload(sys.argv[1:])
  File "examdownloader-cli.py", line 33, in startDownload
    ed.getContents(module, username, password, destination, downloadCallback, updateStatus)
  File "/Users/hong/nus-exams-downloader/examdownloader.py", line 14, in getContents
`  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1274, in connect
    server_hostname=server_hostname)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 352, in wrap_socket
    _context=self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 579, in __init__
    self.do_handshake()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 808, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)
```

**Comment by hongshaoyang** [comment]
after some investigation, it is because my macOS python (python 2.7) uses an old version of openSSL which is too old to use TLS 1.2 currently being used by https://libbrs.nus.edu.sg/. 

output of `curl -v -I https://libbrs.nus.edu.sg/infogate/loginAction.do?execution=login`:
```
*   Trying 137.132.5.48...
* TCP_NODELAY set
* Connected to libbrs.nus.edu.sg (137.132.5.48) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
```

the alternative would be to use my cool new python3 which solves the issue
